name: CI / Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - name: Setup Node.js with Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      
      # -  name: Run tests
       # run: npm test -- --silent 

      # Шаг 5: Собираем проект с помощью Webpack
      - name: Build project
        run: npm run build

      # Шаг 6: Загружаем готовую папку dist как артефакт (для отладки)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # Шаг 7: Публикуем сайт на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4